name: BukkitBackup
main: com.randude14.backup.BukkitBackup
author: Randude14
description: 'Bukkit plugin for backing up your worlds'
version: 1.0
commands: 
    backup: 
        description: 'The overall plugin for BukkitBackup'